### PR TITLE
Fix #3070 - Fixes wrong group display

### LINKED ISSUE #3070: Searching for groups while creating center is displaying groups which are already member of other center
1) Go to centers and create a center. 
2) While creating center search for existing groups and select the group which is already part of other center.

Expected: The application should not show the groups which are part of other centers. 

Moved from: https://issues.apache.org/jira/browse/FINERACT-589

### PR DESCRIPTION
**Pull request by OHassini**
## Description
Made the application only show the groups which are not part of other centers when creating a center.
## Related issues and discussion
#3070 

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by OHassini** [comment]
@abhaychawla Hi, please have a look !!

File: app/scripts/controllers/centers/CreateCenterController.js [hunk 1]
```diff
@@ -21,6 +21,11 @@
             scope.getGroups = function() {
                 resourceFactory.groupResource.getAllGroups({officeId: scope.formData.officeId }, function (data) {
                     scope.groups = data;
+                    for (var i = 0; i<scope.groups.length; i++) {
+                        if (scope.groups[i].centerName) {
+                            scope.groups.splice(i, 1);
+                        }
+                    }
```
Comment (abhaychawla) [inline app/scripts/controllers/centers/CreateCenterController.js]: There is an issue with this approach. As you are iterating over the array using a for loop and at the same time modifying it with `splice`, there might be unexpected results in some cases as elements are removed from the array and its length is modified during iteration. Try using `filter` method instead. Also, the id parameter of the center can be used instead of name for filtering.

**Review by abhaychawla — CHANGES_REQUESTED** [review]

**Comment by OHassini** [comment]
@abhaychawla Done !! and to be honest it's way cleaner using this method.

**Review by abhaychawla — APPROVED** [review]
Good work!!

**Comment by abhaychawla** [comment]
@luckyman20 Please merge this.
